# Generated by Django 5.2.4 on 2025-07-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interested_genres',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='looking_genres',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interested_genres',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='home.genre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='looking_genres',
            field=models.ManyToManyField(blank=True, related_name='looking_users', to='home.genre'),
        ),
    ]
