# Generated by Django 5.2.4 on 2025-08-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[("Available", "Available"), ("Exchanged", "Exchanged")],
                default="Available",
                max_length=10,
            ),
        ),
    ]
