# Generated by Django 5.2.4 on 2025-09-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_review"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="review",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("buyer_review", "Review by Buyer"),
                    ("seller_review", "Review by Seller"),
                ],
                default="buyer_review",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="book_rating",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
            ),
        ),
    ]
