# Generated by Django 5.2.4 on 2025-08-31 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_book_exchanged_with"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_books", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
