# Generated by Django 5.2.4 on 2025-09-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_book_favorited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
