# Generated by Django 5.2.4 on 2025-09-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
