# Generated by Django 5.2.4 on 2025-09-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_book_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="condition",
        ),
        migrations.AddField(
            model_name="book",
            name="condition_rating",
            field=models.IntegerField(
                choices=[
                    (5, "★★★★★ Excellent"),
                    (4, "★★★★☆ Very Good"),
                    (3, "★★★☆☆ Good"),
                    (2, "★★☆☆☆ Fair"),
                    (1, "★☆☆☆☆ Poor"),
                ],
                default=3,
            ),
        ),
    ]
